id = "pebble"
name = "Pebble"
version = "0.1.10"
schema_version = 1
grammar = "pebble"
authors = ["Caleb Otto", "Joshua Pepple"]
repository = "https://github.com/pepplejoshua/pebble"

[grammars.pebble]
repository = "https://github.com/Caleb-o/pebble-grammar"
rev = "b1b5024fdc3e54c9bd17630e304ad119a292fbcf"
