id = "pebble"
name = "Pebble"
version = "0.1.11"
schema_version = 1
grammar = "pebble"
authors = ["Caleb Otto", "Joshua Pepple"]
repository = "https://github.com/pepplejoshua/pebble"

[grammars.pebble]
repository = "https://github.com/Caleb-o/pebble-grammar"
rev = "c5aacafd7e6803b1da31fe1a245dce8ea2fe40e2"
