id = "pebble"
name = "Pebble"
version = "0.13.0"
schema_version = 1
grammar = "pebble"
authors = ["Caleb Otto", "Joshua Pepple"]
repository = "https://github.com/pepplejoshua/pebble"

[grammars.pebble]
repository = "https://github.com/Caleb-o/pebble-grammar"
rev = "07f35b0d2ab09a03f6981787bc3297960b856d17"
