id = "pebble"
name = "Pebble"
version = "0.1.9"
schema_version = 1
grammar = "pebble"
authors = ["Caleb Otto", "Joshua Pepple"]
repository = "https://github.com/pepplejoshua/pebble"

[grammars.pebble]
repository = "https://github.com/Caleb-o/pebble-grammar"
rev = "49d5b0d4e442e72447e91ac6c34f2b69b467ec89"
