id = "pebble"
name = "Pebble"
version = "0.1.8"
schema_version = 1
grammar = "pebble"
authors = ["Caleb Otto", "Joshua Pepple"]
repository = "https://github.com/pepplejoshua/pebble"

[grammars.pebble]
repository = "https://github.com/Caleb-o/pebble-grammar"
rev = "cba4e2a80e8a9e68f72bbaa43f9717e1cc6b1266"
