id = "pebble"
name = "Pebble"
version = "0.1.12"
schema_version = 1
grammar = "pebble"
authors = ["Caleb Otto", "Joshua Pepple"]
repository = "https://github.com/pepplejoshua/pebble"

[grammars.pebble]
repository = "https://github.com/Caleb-o/pebble-grammar"
rev = "586e82002d9725f1a42a86584c237b95b665f0c3"
